// const GAME = {
//   LOAD: "REQUEST_GAMES_DATA",
//   LOAD_SUCCESS: "RECEIVE_GAMES_DATA",
// };

// export default GAME;
export enum gameTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
}
